#:schema node_modules/wrangler/config-schema.json
name = "my-hono-app"
main = "src/index.ts"
compatibility_date = "2024-10-22"


# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "27fd3b6c-864c-4f6d-a7db-79835f3c1306"
preview_database_id = "27fd3b6c-864c-4f6d-a7db-79835f3c1306"
migrations_dir = "migrations"